export const PERMISSIONS = {
  DASHBOARD: {
    ACCESS: 'Permissions.Dashboard.Access',
    VIEW: 'Permissions.Dashboard.View',
  },
  SUBSIDIARY: {
    ACCESS: 'Permissions.Company.Access',
    VIEW: 'Permissions.Company.View',
    CREATE: 'Permissions.Company.Create',
    UPDATE: 'Permissions.Company.Update',
    DELETE: 'Permissions.Company.Delete',
    SEARCH: 'Permissions.Company.Search',
  },
  DEPARTMENT: {
    ACCESS: 'Permissions.Department.Access',
    VIEW: 'Permissions.Department.View',
    CREATE: 'Permissions.Department.Create',
    UPDATE: 'Permissions.Department.Update',
    DELETE: 'Permissions.Department.Delete',
    SEARCH: 'Permissions.Department.Search',
  },
  SECTION: {
    ACCESS: 'Permissions.Section.Access',
    VIEW: 'Permissions.Section.View',
    CREATE: 'Permissions.Section.Create',
    UPDATE: 'Permissions.Section.Update',
    DELETE: 'Permissions.Section.Delete',
    SEARCH: 'Permissions.Section.Search',
  },
  SUB_SECTION: {
    ACCESS: 'Permissions.SubSection.Access',
    VIEW: 'Permissions.SubSection.View',
    CREATE: 'Permissions.SubSection.Create',
    UPDATE: 'Permissions.SubSection.Update',
    DELETE: 'Permissions.SubSection.Delete',
    SEARCH: 'Permissions.SubSection.Search',
  },
  USER: {
    ACCESS: 'Permissions.Users.Access',
    VIEW: 'Permissions.Users.View',
    CREATE: 'Permissions.Users.Create',
    UPDATE: 'Permissions.Users.Update',
    DELETE: 'Permissions.Users.Delete',
    DEACTIVATE: 'Permissions.Users.Deactivate',
    SEARCH: 'Permissions.Users.Search',
  },
  RISK_UNIVERSE: {
    ACCESS: 'Permissions.RiskUniverse.Access',
    VIEW: 'Permissions.RiskUniverse.View',
    CREATE: 'Permissions.RiskUniverse.Create',
    UPDATE: 'Permissions.RiskUniverse.Update',
    DELETE: 'Permissions.RiskUniverse.Delete',
    SEARCH: 'Permissions.RiskUniverse.Search',
    ASSESS: 'Permissions.RiskUniverse.Assess',
  },
  RISK_INCIDENT: {
    ACCESS: 'Permissions.RiskUniverse.Access',
    VIEW: 'Permissions.RiskUniverse.View',
    CREATE: 'Permissions.RiskUniverse.Create',
    UPDATE: 'Permissions.RiskUniverse.Update',
    DELETE: 'Permissions.RiskUniverse.Delete',
    SEARCH: 'Permissions.RiskUniverse.Search',
  },
  RISK_ASSESSMENT: {
    ACCESS: 'Permissions.SubSection.Access',
    VIEW: 'Permissions.SubSection.View',
    CREATE: 'Permissions.SubSection.Create',
    UPDATE: 'Permissions.SubSection.Update',
    DELETE: 'Permissions.SubSection.Delete',
    SEARCH: 'Permissions.SubSection.Search',
  },
  STATUTORY_COMPLIANCE: {
    ACCESS: 'Permissions.StatutoryCompliance.Access',
    VIEW: 'Permissions.StatutoryCompliance.View',
    CREATE: 'Permissions.StatutoryCompliance.Create',
    UPDATE: 'Permissions.StatutoryCompliance.Update',
    DELETE: 'Permissions.StatutoryCompliance.Delete',
    SEARCH: 'Permissions.StatutoryCompliance.Search',
    APPROVE: 'Permissions.StatutoryCompliance.Approve',
  },
  ENTERPRISE_COMPLIANCE: {
    ACCESS: 'Permissions.EnterpriseCompliance.Access',
    VIEW: 'Permissions.EnterpriseCompliance.View',
    CREATE: 'Permissions.EnterpriseCompliance.Create',
    UPDATE: 'Permissions.EnterpriseCompliance.Update',
    DELETE: 'Permissions.EnterpriseCompliance.Delete',
    SEARCH: 'Permissions.EnterpriseCompliance.Search',
  },
  LEGAL_COMPLIANCE: {
    ACCESS: 'Permissions.LegalCompliance.Access',
    VIEW: 'Permissions.LegalCompliance.View',
    CREATE: 'Permissions.LegalCompliance.Create',
    UPDATE: 'Permissions.LegalCompliance.Update',
    DELETE: 'Permissions.LegalCompliance.Delete',
    SEARCH: 'Permissions.LegalCompliance.Search',
  },
  ROLE: {
    ACCESS: 'Permissions.Roles.Access',
    VIEW: 'Permissions.Roles.View',
    CREATE: 'Permissions.Roles.Create',
    UPDATE: 'Permissions.Roles.Update',
    DELETE: 'Permissions.Roles.Delete',
    SEARCH: 'Permissions.Roles.Search',
  },
  RISK_PARAM: {
    ACCESS: 'Permissions.RiskParameters.Access',
    VIEW: 'Permissions.RiskParameters.View',
    CREATE: 'Permissions.RiskParameters.Create',
    UPDATE: 'Permissions.RiskParameters.Update',
    DELETE: 'Permissions.RiskParameters.Delete',
    SEARCH: 'Permissions.RiskParameters.Search',
  },
  RISK_INDICATOR: {
    ACCESS: 'Permissions.RiskIndicator.Access',
    VIEW: 'Permissions.RiskIndicator.View',
    CREATE: 'Permissions.RiskIndicator.Create',
    UPDATE: 'Permissions.RiskIndicator.Update',
    DELETE: 'Permissions.RiskIndicator.Delete',
    SEARCH: 'Permissions.RiskIndicator.Search',
  },
};
